project:
  type: website
  output-dir: docs
website:
  title: "Pedro Abelin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Research.qmd
        text: Research
      - href: Interviews.qmd
        text: Interviews

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

