project:
  type: website
  output-dir: docs
website:
  title: "pedroabelin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Research.qmd
        text: Research
      - href: https://www.tandfonline.com/doi/abs/10.1080/1369118X.2018.1451550
        text: Test

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

