project:
  type: website
  output-dir: docs
website:
  title: "Pedro Abelin!"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Research.qmd
        text: Research
      - href: Interviews.qmd
        text: Interviews
      - href: Magazine Articles.qmd
        text: Magazine Articles
      - href: Analysis.qmd
        text: Analysis
      - href: Where you can find me.qmd
        text: Where you can find me

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

